default:
  image:
    name: europe-west1-docker.pkg.dev/malt-build/malt-tap-docker/pnpm:6.32.4
    entrypoint: []

stages:
  - build
  - deploy

.common:
  tags:
    - malt-build
  retry:
    max: 2
    when:
      - unknown_failure
      - stale_schedule
      - runner_system_failure
      - stuck_or_timeout_failure


.build:
  stage: build
  script:
    - cd ${CONTEXT_DIR}
    - npm install
    - pnpm build
  artifacts:
    paths:
      - ${CONTEXT_DIR}/dist/
      - ${CONTEXT_DIR}/README.md
      - ${CONTEXT_DIR}/package.json
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push"
#      changes:
#        - ${CONTEXT_DIR}/**/*

build-layout:
  extends:
    - .common
    - .build
  variables:
    CONTEXT_DIR: layout

build-core:
  extends:
    - .common
    - .build
  variables:
    CONTEXT_DIR: core

build-tokens:
  extends:
    - .common
    - .build
  variables:
    CONTEXT_DIR: tokens

.npm-publish:
  stage: deploy
  script:
    - cd ${CONTEXT_DIR}
    - echo "//registry.npmjs.org/:_authToken="${NPM_AUTH_TOKEN} > .npmrc
    - npm login
    - npm publish
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

npm-publish-layout:
  extends:
    - .npm-publish
    - .common
  dependencies: ["build-layout"]
  variables:
    CONTEXT_DIR: layout

npm-publish-core:
  extends:
    - .npm-publish
    - .common
  dependencies: ["build-core"]
  variables:
    CONTEXT_DIR: core

npm-publish-tokens:
  extends:
    - .npm-publish
    - .common
  dependencies: ["build-tokens"]
  variables:
    CONTEXT_DIR: tokens