default:
  image:
    name: europe-west1-docker.pkg.dev/malt-build/malt-tap-docker/pnpm:6.32.4/malt/malt-builder:pnpm3d9e4e8d3fd7f84e881ae004477832a7e7d59f7b875d303c4a441531bc650ddd
    entrypoint: []

stages:
  - build
  - npm_publish
  - cdn_publish

.common:
  tags:
    - malt-build
  retry:
    max: 2
    when:
      - unknown_failure
      - stale_schedule
      - runner_system_failure
      - stuck_or_timeout_failure


.build:
  stage: build
  script:
    - cd ${CONTEXT_DIR}
    - pnpm install
    - pnpm build
  artifacts:
    paths:
      - ${CONTEXT_DIR}/dist/
      - ${CONTEXT_DIR}/README.md
      - ${CONTEXT_DIR}/package.json
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push"
#      changes:
#        - ${CONTEXT_DIR}/**/*

build-layout:
  extends:
    - .common
    - .build
  variables:
    CONTEXT_DIR: layout

build-core:
  extends:
    - .common
    - .build
  variables:
    CONTEXT_DIR: core

build-tokens:
  extends:
    - .common
    - .build
  variables:
    CONTEXT_DIR: tokens

.npm-publish:
  stage: npm_publish
  script:
    - cd ${CONTEXT_DIR}
    - echo "//registry.npmjs.org/:_authToken="${NPM_AUTH_TOKEN} > .npmrc
    - ls -l
    - npm publish
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

npm-publish-layout:
  extends:
    - .npm-publish
    - .common
  dependencies: ["build-layout"]
  variables:
    CONTEXT_DIR: layout

npm-publish-core:
  extends:
    - .npm-publish
    - .common
  dependencies: ["build-core"]
  variables:
    CONTEXT_DIR: core

npm-publish-tokens:
  extends:
    - .npm-publish
    - .common
  dependencies: ["build-tokens"]
  variables:
    CONTEXT_DIR: tokens

.publish-cdn:
  stage: cdn_publish
  image: europe-west1-docker.pkg.dev/malt-build/malt-tap-docker/malt/malt-builder:fc6e6b7d60b6a5cf2952f22a0f9323267b0c7dea69b991ad83e2c34f5ed08840
  extends:
    - .common
  dependencies: ["build-core"]
  variables:
    SOURCE_CDN_DIR: dist
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - cd core
    - PACKAGE_VERSION=$(jq -r .version package.json)
    - if gsutil ls ${TARGET_CDN_BUCKET}/${PACKAGE_VERSION} ; then exit 1; fi
    - echo "Deploying assets in '${SOURCE_CDN_DIR}' to ${TARGET_CDN_BUCKET}/${PACKAGE_VERSION}"
    - gsutil -h "Cache-Control:no-transform,public,max-age=2592000" -m cp -z js,css,html,json -r "${SOURCE_CDN_DIR}/"* "${TARGET_CDN_BUCKET}/${PACKAGE_VERSION}" 2>&1 | grep -v "Done"

publish-cdn-integration:
  extends:
    - .publish-cdn
  variables:
    TARGET_CDN_BUCKET: gs://malt-integration-cdn-regional/npm/@maltjoy/core

publish-cdn-production:
  extends:
    - .publish-cdn
  variables:
    TARGET_CDN_BUCKET: gs://malt-production-cdn-regional/npm/@maltjoy/core